CREATE TABLE comments (
  id        VARCHAR NOT NULL PRIMARY KEY,
  userId    VARCHAR NOT NULL,
  postId    VARCHAR NOT NULL,
  comment   VARCHAR NOT NULL,
  postedAt  INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (PostId) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE TABLE likes (
  userId    VARCHAR NOT NULL,
  postId    VARCHAR NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (postId) REFERENCES posts (id) ON DELETE CASCADE,
  PRIMARY KEY (userId, postId)
);