export enum Errors {
  ALL_FIELDS_REQUIRED = "All Fields are required",
  INVALID_EMAIL = "Email is invalid",
  INVALID_USERNAME = "Username is invalid",
  INVALID_PASSWORD = "Password is invalid",
  INVALID_URL = "URL is invalid",
  USER_ALREADY_EXIST = "User already exist",
  WRONG_CREDENTIALS = "Wrong Credentials",
  BAD_TOKEN = "Bad Token",
  COMMENT_NOT_EMPTY = "Comment cannot be empty",
  COMMENT_NOT_EXIST = "Comment does not exist",
  LIKE_ALREADY_EXIST = "Like already exist",
  LIKE_NOT_EXIST = "Like does not exist",
  MISSING_USER_ID = "User ID is required but missing",
  MISSING_POST_ID = "Post ID is required but missing",
  MISSING_COMMENT_ID = "Comment ID is required but missing",
  MISSING_LIKE_ID = "Like ID is required but missing",
  MISSING_TITLE = "Title is required but missing",
  MISSING_URL = "URL is required but missing",
  MISSING_CONTENT = "Content is required but missing",
  USER_NOT_FOUND = "User not found",
}
